/**
 * This file is autogenerated by Scaffold-Stark.
 * You should not edit it manually or your changes might be overwritten.
 */

const deployedContracts = {
  devnet: {
    BitcoinSignature: {
      address:
        "0x2bd336532875c6d4e2ee60ca4332f3bea2225d046a80b4da9c70d596fc6ea2c",
      abi: [
        {
          type: "impl",
          name: "BitcoinSignatureImpl",
          interface_name: "contracts::BitcoinSignature::IBitcoinSignature",
        },
        {
          type: "struct",
          name: "core::integer::u256",
          members: [
            {
              name: "low",
              type: "core::integer::u128",
            },
            {
              name: "high",
              type: "core::integer::u128",
            },
          ],
        },
        {
          type: "struct",
          name: "contracts::bitcoin::Secp256Signature",
          members: [
            {
              name: "r",
              type: "core::integer::u256",
            },
            {
              name: "s",
              type: "core::integer::u256",
            },
          ],
        },
        {
          type: "struct",
          name: "contracts::bitcoin::BitcoinPublicKey",
          members: [
            {
              name: "x",
              type: "core::integer::u256",
            },
            {
              name: "y",
              type: "core::integer::u256",
            },
          ],
        },
        {
          type: "enum",
          name: "core::bool",
          variants: [
            {
              name: "False",
              type: "()",
            },
            {
              name: "True",
              type: "()",
            },
          ],
        },
        {
          type: "struct",
          name: "core::byte_array::ByteArray",
          members: [
            {
              name: "data",
              type: "core::array::Array::<core::bytes_31::bytes31>",
            },
            {
              name: "pending_word",
              type: "core::felt252",
            },
            {
              name: "pending_word_len",
              type: "core::integer::u32",
            },
          ],
        },
        {
          type: "interface",
          name: "contracts::BitcoinSignature::IBitcoinSignature",
          items: [
            {
              type: "function",
              name: "verify_message",
              inputs: [
                {
                  name: "message",
                  type: "core::integer::u256",
                },
                {
                  name: "signature",
                  type: "contracts::bitcoin::Secp256Signature",
                },
                {
                  name: "public_key",
                  type: "contracts::bitcoin::BitcoinPublicKey",
                },
              ],
              outputs: [
                {
                  type: "core::bool",
                },
              ],
              state_mutability: "view",
            },
            {
              type: "function",
              name: "step1",
              inputs: [
                {
                  name: "message",
                  type: "core::felt252",
                },
              ],
              outputs: [
                {
                  type: "core::integer::u256",
                },
              ],
              state_mutability: "view",
            },
            {
              type: "function",
              name: "sha256",
              inputs: [
                {
                  name: "message",
                  type: "core::byte_array::ByteArray",
                },
              ],
              outputs: [
                {
                  type: "core::bool",
                },
              ],
              state_mutability: "view",
            },
          ],
        },
        {
          type: "event",
          name: "contracts::BitcoinSignature::BitcoinSignature::BitcoinMessageHashing",
          kind: "struct",
          members: [
            {
              name: "step1",
              type: "core::integer::u256",
              kind: "key",
            },
            {
              name: "step2",
              type: "core::integer::u256",
              kind: "data",
            },
          ],
        },
        {
          type: "event",
          name: "contracts::BitcoinSignature::BitcoinSignature::Event",
          kind: "enum",
          variants: [
            {
              name: "BitcoinMessageHashing",
              type: "contracts::BitcoinSignature::BitcoinSignature::BitcoinMessageHashing",
              kind: "nested",
            },
          ],
        },
      ],
      classHash:
        "0x509249e7ed8e63f3dc3e1ffbe2d4dd1b505e05397a07009dda4195681e23325",
    },
  },
  sepolia: {
    BitcoinSignature: {
      address:
        "0x173bc2ce772615c2c6918017aa6d86fd863cee059519dbc34696f5e357b062c",
      abi: [
        {
          type: "impl",
          name: "BitcoinSignatureImpl",
          interface_name: "contracts::BitcoinSignature::IBitcoinSignature",
        },
        {
          type: "struct",
          name: "core::integer::u256",
          members: [
            {
              name: "low",
              type: "core::integer::u128",
            },
            {
              name: "high",
              type: "core::integer::u128",
            },
          ],
        },
        {
          type: "struct",
          name: "contracts::bitcoin::Secp256Signature",
          members: [
            {
              name: "r",
              type: "core::integer::u256",
            },
            {
              name: "s",
              type: "core::integer::u256",
            },
          ],
        },
        {
          type: "struct",
          name: "contracts::bitcoin::BitcoinPublicKey",
          members: [
            {
              name: "x",
              type: "core::integer::u256",
            },
            {
              name: "y",
              type: "core::integer::u256",
            },
          ],
        },
        {
          type: "enum",
          name: "core::bool",
          variants: [
            {
              name: "False",
              type: "()",
            },
            {
              name: "True",
              type: "()",
            },
          ],
        },
        {
          type: "struct",
          name: "core::byte_array::ByteArray",
          members: [
            {
              name: "data",
              type: "core::array::Array::<core::bytes_31::bytes31>",
            },
            {
              name: "pending_word",
              type: "core::felt252",
            },
            {
              name: "pending_word_len",
              type: "core::integer::u32",
            },
          ],
        },
        {
          type: "interface",
          name: "contracts::BitcoinSignature::IBitcoinSignature",
          items: [
            {
              type: "function",
              name: "verify_message",
              inputs: [
                {
                  name: "message",
                  type: "core::integer::u256",
                },
                {
                  name: "signature",
                  type: "contracts::bitcoin::Secp256Signature",
                },
                {
                  name: "public_key",
                  type: "contracts::bitcoin::BitcoinPublicKey",
                },
              ],
              outputs: [
                {
                  type: "core::bool",
                },
              ],
              state_mutability: "view",
            },
            {
              type: "function",
              name: "step1",
              inputs: [
                {
                  name: "message",
                  type: "core::felt252",
                },
              ],
              outputs: [
                {
                  type: "core::integer::u256",
                },
              ],
              state_mutability: "view",
            },
            {
              type: "function",
              name: "sha256",
              inputs: [
                {
                  name: "message",
                  type: "core::byte_array::ByteArray",
                },
              ],
              outputs: [
                {
                  type: "core::bool",
                },
              ],
              state_mutability: "view",
            },
          ],
        },
        {
          type: "event",
          name: "contracts::BitcoinSignature::BitcoinSignature::BitcoinMessageHashing",
          kind: "struct",
          members: [
            {
              name: "step1",
              type: "core::integer::u256",
              kind: "key",
            },
            {
              name: "step2",
              type: "core::integer::u256",
              kind: "data",
            },
          ],
        },
        {
          type: "event",
          name: "contracts::BitcoinSignature::BitcoinSignature::Event",
          kind: "enum",
          variants: [
            {
              name: "BitcoinMessageHashing",
              type: "contracts::BitcoinSignature::BitcoinSignature::BitcoinMessageHashing",
              kind: "nested",
            },
          ],
        },
      ],
      classHash:
        "0xcec83a5574e95e6dd6a29799513eaac0e9713576f2959be4bbda0e7eca856a",
    },
  },
} as const;

export default deployedContracts;
